### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by IoriMaboroshi** [MlgmXyysd/MeowPage-MlgmXyysd-Friends#14]
名称：伊緻幻の主页

图标：https://b.chwin.asia/wp-content/uploads/2022/11/cropped-lab.magiconch.com90s-time-machine-1667800846069.jpg

域名：https://www.chwin.asia

描述：Take my hands.

**Comment by IoriMaboroshi** [comment]
已添加贵站
![22-12-09-103359](https://user-images.githubusercontent.com/117876175/206611075-0a66bf57-9dfa-4b57-b159-a44fa7d4097f.png)
不知这样可否？

**Comment by MlgmXyysd** [comment]
图标无法获取(521)，服务恢复后更新图标

**Comment by IoriMaboroshi** [comment]
图标已恢复
